// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjlssrqjprvygxrhrnoz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqbHNzcnFqcHJ2eWd4cmhybm96Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkwNzAzMTUsImV4cCI6MjA4NDY0NjMxNX0.lIUJruAG_kFKxfEiIfsiUBgRscn2tfeUOwumgO5x1lU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});